#! /bin/sh

#
# Detect what directory this script is running in, useful to run sibling
# scripts in the same directory.
#
# Code from:
# http://stackoverflow.com/questions/59895/can-a-bash-script-tell-what-directory-its-stored-in
#
# To capture return string:   DIR=$(ScriptDirectory)
# To echo to stdout:          ScriptDirectory
#
function ScriptDirectory
{
    local SOURCE="${BASH_SOURCE[0]}"
    local DIR="$( dirname "$SOURCE" )"
    while [ -h "$SOURCE" ]; do 
      SOURCE="$(readlink "$SOURCE")"
      [[ $SOURCE != /* ]] && SOURCE="$DIR/$SOURCE"
      DIR="$( cd -P "$( dirname "$SOURCE"  )" && pwd )"
    done
    DIR="$( cd -P "$( dirname "$SOURCE" )" && pwd )"

    echo $DIR
}

# Directory of github clone
M="msdn-js"

# Directory of this script (so it can find python scripts next to it)
SCRIPTDIR=$(ScriptDirectory)

# Clone from github if not already present
if [ ! -d "${M}" ]; then
    echo "Cloning from github..."
    git clone https://github.com/webplatform/msdn-js.git
    if [ ! -d "${M}" ]; then
        echo "ERROR: Unable to clone source files from github"
        exit 1
    fi
fi

# Change to cloned repository directory
cd "${M}"

echo "Verify files are well-formed"
if [ ! -f "ZZZ-xmllint" ]; then
    # Don't repeat this step
    touch "ZZZ-xmllint"

    # Run xmllint on each to ensure each file is well-formed XML
    for file in *.html; do
        echo "==== $file"
        if [ "$file" = "js_toc.html" ]; then
            echo "Ignoring non-content file"
            continue
        fi

        # See if xmllint reports non-well-formed XML
        if [ ! "$(xmllint --nonet --noout $file 2>&1 | wc -c)" = "0" ]; then
            echo "ERROR: xmllint reported a problem"
            exit 1
        fi
    done
fi

# Fix file name anomaly
echo "Fixing file name anomaly"
if [ ! -f "Conditional__Ternary-Operator.html" ]; then
    echo "Renaming file"
    mv 'Conditional__Ternary)-Operator.html' 'Conditional__Ternary-Operator.html'
    echo "Editing js_toc.html"
    TMPFILE=$(mktemp)
    sed 's/a href="Conditional__Ternary.html"/a href="Conditional__Ternary-Operator.html"/' js_toc.html > "$TMPFILE"
    mv "$TMPFILE" js_toc.html
fi

# For better readability, reformat the XML
echo "Formatting files in place for readability"
if [ ! -f "ZZZ-reformat" ]; then
    # Don't repeat this step
    touch "ZZZ-reformat"

    for file in *.html; do
        echo "==== $file"
        if [ "$file" = "js_toc.html" ]; then
            echo "Ignoring non-content file"
            continue
        fi
        TMPFILE=$(mktemp)
        xmllint --nonet --format "$file" > "$TMPFILE"
        mv "$TMPFILE" "$file"
    done
fi

#
# Fix internal links within files by grabbing from each file "FILENAME":
#   <meta name="Microsoft.Help.Id" content="ac6ad343-7663-406a-a2b7-4cc5025ca3d6"/>
# and every anchor linking to that in all files, replace:
#   <a href="1c46a560-ec8d-41c5-a806-30c4843789c4.htm">
# with:
#   <a href="FILENAME">
#
echo "Fix internal links within files"
if [ ! -f "ZZZ-internallinks" ]; then
    # Don't repeat this step
    touch "ZZZ-internallinks"

    for file in *.html; do
        echo "==== $file"
        if [ "$file" = "js_toc.html" ]; then
            echo "Ignoring non-content file"
            continue
        fi

        # Grab the content attribute value from meta element with name="Microsoft.Help.Id"
        HELP_ID=$(grep 'meta name="Microsoft.Help.Id"' $file | sed 's/^.*content="\([^"]*\)".*$/\1/')
        echo "Fixing links to ${HELP_ID}.htm"
        for fix in $(grep -l "${HELP_ID}.htm" *.html); do
            echo "    $fix"
            TMPFILE=$(mktemp)
            sed "s/${HELP_ID}.htm/${file}/" "$fix" > "$TMPFILE"
            mv "$TMPFILE" "$fix"
        done
    done
fi

#
# Convert JavaScript-Reference.html, only <div id="mainBody">, into new section
# of page http://docs.webplatform.org/wiki/javascript
#
# Rule: div id becomes new section but only if it has non-whitespace text node children,
#       use the div id as the section name.
# Rule: p becomes double-newline separated paragraphs, using only text node children.
# Rule: h1 text children nodes (might be h1/span) becomes "==text=="
# Rule: ul/li become "* text"
# Rule: dl/dt becomes "; text"
#       dl/dd becomes ": text" (same line as above)
#
echo "Converting JavaScript-Reference.html"
TMPFILE=$(mktemp)
"${SCRIPTDIR}/simple-convert" "JavaScript-Reference.html" "mainBody" > "$TMPFILE"
if [ ! $? = 0 ]; then
    echo "ERROR: problem discovered"
    rm "$TMPFILE"
    exit 1
fi
mv "$TMPFILE" "JavaScript-Reference.html"

# # Extract title of each file to demo reading XML in Python
# echo "Beginning processing pipeline"
# echo "Phase 1"
# for file in *.html; do
#     echo "==== $file"
#     if [ "$file" = "js_toc.html" ]; then
#         echo "Ignoring non-content file"
#         continue
#     fi
# 
#     "${SCRIPTDIR}/phase-01" "$file"
#     if [ ! $? = 0 ]; then
#         echo "ERROR: problem discovered"
#         exit 1
#     fi
# done

# Success if we got here without exiting early
echo "SUCCESS"
