#! /usr/bin/env python
'''
Extract the filename to wiki page name mapping from a table of contents
html file.
'''

import sys
from xml.etree import ElementTree

usage = "Usage: extract-mapping INPUTFILE ELEMENTID"

# Parse args
if len (sys.argv) != 3:
    raise Exception ("ERROR: Invalid number of arguments\n{:}".format (usage))
inputfile = sys.argv[1]
elementid = sys.argv[2]

# Parse XML file and find element having given id
tree = ElementTree.parse (inputfile)
root = tree.getroot ()
element = root.find (".[@id='{:}']".format (elementid))
if (element is None):
    element = root.find (".//*[@id='{:}']".format (elementid, elementid))

# See if we found it
if (element is None):
    raise Exception ("ERROR: Unable to find element having id {:}".format (elementid))

def mapChildren (element, subpages):
    '''
    Recurse element children
    '''
    for child in element:
        prefix='/'.join (subpages)
        if (prefix is None or prefix == ""):
            print ("{:}".format (child.tag))
        else:
            print ("{:}/{:}".format ('/'.join (subpages), child.tag))
        subpages.append (child.tag)
        mapChildren (child, subpages)
        subpages.pop ()

# Start walking element recursively applying various rules
mapChildren (element, subpages=[])
