#! /usr/bin/env python

import sys
from xml.etree import ElementTree

for file in sys.argv[1:]:
    tree = ElementTree.parse (file)
    root = tree.getroot ()
    head = root.find ("head")
    body = root.find ("body")
    headTitle = head.find ("title")
    
    print ("Title: {:}".format (headTitle.text))
