#! /usr/bin/env python
'''
Convert an html file into MediaWiki syntax.
'''

import sys
from xml.etree import ElementTree

usage = "Usage: simple-convert INPUTFILE ELEMENTID"

# Parse args
if len (sys.argv) != 3:
    raise Exception ("ERROR: Invalid number of arguments\n" + usage)
inputfile = sys.argv[1]
elementid = sys.argv[2]
print ("Reading {:} looking for element id {:}".format (inputfile, elementid))

# Parse XML file and find element having given id
tree = ElementTree.parse (inputfile)
root = tree.getroot ()
element = root.find (".//*[@id='{:}']".format (elementid))
if (element is None):
    raise Exception ("ERROR: Unable to find element having id {:}".format (elementid))

def allText (element):
    '''
    Returns whitespace-stripped concatenated child text node values, or None if empty.
    '''
    textFragments = []
    for part in element.itertext ():
        less = part.strip ()
        if (less != ""):
            textFragments.append (less)
    if (len (textFragments) == 0):
        return None
    else:
        return ''.join (textFragments)

def convertChildren (element, sectionDepth, listDepth, parents):
    '''
    Call convert on each child of element, the driver for recursion.
    '''
    parents.append (element.tag)
    for child in element:
        convert (child, sectionDepth, listDepth, parents)
    parents.pop ()

def convert_p (element, sectionDepth, listDepth, parents):
    '''
    Convert a paragraph into MediaWiki syntax.

    Rule: p becomes double-newline separated paragraphs, using only text node children.
    '''
    all = allText (element)
    # Paragraphs need a normal line ending plus one more blank line
    print all + "\n"

def convert_div (element, sectionDepth, listDepth, parents):
    '''
    Convert a paragraph into MediaWiki syntax.

    Rule: div id becomes new section but only if it has non-whitespace text node children,
          use the div id as the section name.
    '''
    # sectionName = element.get ('id')
    # if (sectionName is None):
    #     sectionName = "unknown"
    # print "=" * sectionDepth + sectionName + "=" * sectionDepth
    convertChildren (element, sectionDepth + 1, listDepth, parents)

def convert_h1 (element, sectionDepth, listDepth, parents):
    '''
    Convert a heading into MediaWiki syntax.

    Rule: h1 text children nodes becomes "==text==", ignoring intermediate elements
          like span in the case of h1/span.
    '''
    all = allText (element)
    # Headers turn into sections with the right number of equals signs
    print "\n" + "=" * sectionDepth + all + "=" * sectionDepth

def convert_ul (element, sectionDepth, listDepth, parents):
    '''
    Convert a paragraph into MediaWiki syntax.

    Rule: ul/li become "* text"
    '''
    # Unordered lists we simply recurse and then 'li' gets converted
    convertChildren (element, sectionDepth, listDepth + 1, parents)

def convert_li (element, sectionDepth, listDepth, parents):
    '''
    Convert a paragraph into MediaWiki syntax.

    Rule: ul/li become "* text"
    '''
    #@@@TODO -- ensure parent is "ul"
    all = allText (element)
    # List elements turn into the right number of asterisks
    print "*" * listDepth + " " + all

def convert_dl (element, sectionDepth, listDepth, parents):
    '''
    Convert a paragraph into MediaWiki syntax.

    Rule: dl/dt becomes "; text"
          dl/dd becomes ": text" (same line as above)
    '''
    # Definition list we simply recurse and the 'dt' gets converted
    convertChildren (element, sectionDepth, listDepth, parents)

def convert_dt (element, sectionDepth, listDepth, parents):
    '''
    Convert a paragraph into MediaWiki syntax.

    Rule: dl/dt becomes "; text"
          dl/dd becomes ": text" (same line as above)
    '''
    #@@@TODO -- ensure parent is "dl"
    all = allText (element)
    # A semicolon and the definition term, expect a 'dd' afterward
    sys.stdout.write ("; " + all)

def convert_dd (element, sectionDepth, listDepth, parents):
    '''
    Convert a paragraph into MediaWiki syntax.

    Rule: dl/dt becomes "; text"
          dl/dd becomes ": text" (same line as above)
    '''
    #@@@TODO -- ensure parent is "dl" (and maybe previous sibling is "dt"?)
    all = allText (element)
    # A definition follows a 'dt' and has a colon and content
    print ": " + all

def convert (element, sectionDepth, listDepth, parents):
    '''
    Convert html element into MediaWiki syntax according to a set of rules.
    '''
    # Grab all the combined text nodes underneath element
    all = allText (element)
    # Skip the element completely if there is no text inside of it anywhere
    if (all is not None):
        if (element.tag == "div"):
            convert_div (element, sectionDepth, listDepth, parents)
        elif (element.tag == "p"):
            convert_p (element, sectionDepth, listDepth, parents)
        elif (element.tag == "h1"):
            convert_h1 (element, sectionDepth, listDepth, parents)
        elif (element.tag == "ul"):
            convert_ul (element, sectionDepth, listDepth, parents)
        elif (element.tag == "li"):
            convert_li (element, sectionDepth, listDepth, parents)
        elif (element.tag == "dl"):
            convert_dl (element, sectionDepth, listDepth, parents)
        elif (element.tag == "dt"):
            convert_dt (element, sectionDepth, listDepth, parents)
        elif (element.tag == "dd"):
            convert_dd (element, sectionDepth, listDepth, parents)

# Start walking element recursively applying various rules
convertChildren (element, sectionDepth=2, listDepth=0, parents=[])
